### PR TITLE
Almost ready :) 

### PR DESCRIPTION
**Pull request by ghost**
I leave the section links to you or other modification you wanna do, I really appriciate that you did, thank you again!

### CODE REVIEW

**Comment by kujtimiihoxha** [comment]
@kataras Thanks for the help, I just wonder why are there changes on the theme folder itself ?

**Comment by kujtimiihoxha** [comment]
@kataras looks like there are no problems with the pull request I will merge it ;)

**Comment by ghost** [comment]
@kujtimiihoxha  

> I just wonder why are there changes on the theme folder itself ?  

I put the static iris content (images) inside the theme, also when I tried to install it using the readme steps it fails, submodules are not always good (especially for newcomers) :p

I thanks you man, you're the first!!

**Comment by kujtimiihoxha** [comment]
@kataras See #2 and tell me what you think.

**Pull request merged**
